# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationstat',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surveystat',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
