# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170121_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationstat',
            name='report_order',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Order in reports'),
        ),
    ]
