# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20170124_1511'),
        ('reports', '0004_auto_20170124_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='question',
        ),
        migrations.AddField(
            model_name='representation',
            name='question',
            field=models.ManyToManyField(to='survey.Question'),
        ),
    ]
