# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20170124_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representation',
            options={'ordering': ['ordering', 'id']},
        ),
        migrations.AddField(
            model_name='questionstat',
            name='type',
            field=models.CharField(choices=[('type_average_percent', 'Average percent representation'), ('type_yes_no', 'Representation for "yes" or "no" answers'), ('type_multiselect_top', 'Top 1 and top 3 representation for ordered multiselect')], max_length=50, null=True, verbose_name='Representation Type'),
        ),
        migrations.AddField(
            model_name='representation',
            name='type',
            field=models.CharField(choices=[('type_average_percent', 'Average percent representation'), ('type_yes_no', 'Representation for "yes" or "no" answers'), ('type_multiselect_top', 'Top 1 and top 3 representation for ordered multiselect')], max_length=50, null=True, verbose_name='Representation Type'),
        ),
    ]
