# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20170124_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
