# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_representation_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationstat',
            options={'ordering': ['ordering', 'id']},
        ),
        migrations.AlterModelOptions(
            name='questionstat',
            options={'ordering': ['ordering', 'id']},
        ),
    ]
