# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 10:13
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_optiondict'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstat',
            name='vars',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
