# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20180107_1921'),
        ('reports', '0010_questionstat_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='question_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repr', to='survey.Question'),
        ),
    ]
