# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 19:22
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Representation = apps.get_model('reports', 'Representation')
    for r in Representation.objects.all():
        r.question_new = r.question.first()
        r.save()


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_representation_question_new'),
    ]

    operations = [
        migrations.RunPython(forward, dummy),
    ]
