# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_questions_to_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='question',
        ),
    ]
