# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_representation_question'),
    ]

    operations = [
        migrations.RenameField('Representation', 'question_new', 'question'),
    ]
