# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_rename_questions_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
