# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-08 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20180107_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation',
            name='survey',
        ),
    ]
