# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_remove_representation_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionstat',
            name='type',
            field=models.CharField(choices=[('type_average_percent', 'Average percent representation'), ('type_yes_no', 'Representation for "yes" or "no" answers'), ('type_multiselect', 'Pie chart for multiselect'), ('type_multiselect_top', 'Top 1 and top 3 representation for ordered multiselect'), ('type_multiselect_top5', 'Top 5 representation for ordered multiselect')], max_length=50, null=True, verbose_name='Representation Type'),
        ),
        migrations.AlterField(
            model_name='representation',
            name='type',
            field=models.CharField(choices=[('type_average_percent', 'Average percent representation'), ('type_yes_no', 'Representation for "yes" or "no" answers'), ('type_multiselect', 'Pie chart for multiselect'), ('type_multiselect_top', 'Top 1 and top 3 representation for ordered multiselect'), ('type_multiselect_top5', 'Top 5 representation for ordered multiselect')], max_length=50, null=True, verbose_name='Representation Type'),
        ),
    ]
