# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20180112_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='highest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Highest'),
        ),
        migrations.AddField(
            model_name='representation',
            name='lowest',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lowest'),
        ),
    ]
