# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_auto_20180629_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='representation',
            name='distribution',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Distribution'),
        ),
    ]
