# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 23:22
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161228_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('users.user', django.contrib.auth.models.AnonymousUser),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
