# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_anonymoususer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['ordering', 'id'], 'verbose_name_plural': 'countries'},
        ),
        migrations.AddField(
            model_name='country',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=1, verbose_name='Order in reports'),
        ),
    ]
