# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170126_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='use_in_reports',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Use in reports'),
        ),
    ]
