# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_country_use_in_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Country slug'),
        ),
    ]
