# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_country_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Language'),
        ),
    ]
