# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171225_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapeuticArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='therapeutic_areas',
            field=models.ManyToManyField(related_name='users', to='users.TherapeuticArea'),
        ),
    ]
