# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-26 20:19
from __future__ import unicode_literals

from django.db import migrations


def create_permission_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    User = apps.get_model('users', 'User')

    g = Group.objects.get_or_create(name='Otsuka User')[0]
    g.permissions.set(
        Permission.objects.filter(codename__in=('add_answer', 'change_answer', 'delete_answer')))
    g.user_set.set(User.objects.all())

    g = Group.objects.get_or_create(name='Otsuka Administrator')[0]
    g.permissions.set(
        Permission.objects.filter(codename__in=('add_country', 'change_country', 'delete_country',
                                                'add_user', 'change_user', 'delete_user')))


def delete_permission_groups(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171225_1341'),
    ]

    operations = [
        migrations.RunPython(create_permission_groups, delete_permission_groups),
    ]
