# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-26 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secondary_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='therapeutic_areas',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.TherapeuticArea'),
        ),
    ]
