# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180110_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='therapeutic_areas',
            field=models.ManyToManyField(blank=True, help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', related_name='users', to='users.TherapeuticArea'),
        ),
    ]
