# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_anonymoususer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCPCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
            ],
            options={
                'verbose_name': 'Category of HCP',
                'verbose_name_plural': 'Categories of HCP',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Option value')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
            ],
            options={
                'ordering': ['question_id', 'ordering', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(1, 'Two dependend fields'), (2, 'For "yes" or "no" answers'), (3, 'Unordered multiselect with "Other" option'), (4, 'Multiselect with ordering and "Other" option'), (11, 'Dependend question for TYPE_TWO_DEPENDEND_FIELDS type')], verbose_name='Question Type')),
                ('field', models.PositiveIntegerField(blank=True, choices=[(1, 'Field with percents'), (2, 'Field number')], null=True, verbose_name='Field Type')),
                ('text', models.CharField(max_length=1000, verbose_name='Question text')),
                ('dependency_type', models.PositiveIntegerField(blank=True, choices=[(1, 'Question is included to other question with TYPE_TWO_DEPENDEND_FIELDS type'), (2, 'Question availability depends of other question')], null=True, verbose_name='Dependency Type')),
                ('script', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Additional script')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
                ('depends_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Region name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
                ('hcp_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.HCPCategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Organization')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of survey')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='Is survey active or not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey')),
            ],
            options={
                'ordering': ['survey_id', 'ordering', 'created_at'],
                'verbose_name': 'Survey Item',
            },
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question'),
        ),
    ]
