# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependency_type',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dependency Type'),
        ),
    ]
