# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_question_dependency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='dependency_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Question is included to other question with TYPE_TWO_DEPENDEND_FIELDS type'), (2, 'Question availability depends of other question')], null=True, verbose_name='Dependency Type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Two dependend fields'), (2, 'For "yes" or "no" answers'), (3, 'Unordered multiselect with "Other" option'), (4, 'Multiselect with ordering and "Other" option'), (11, 'Dependend question for TYPE_TWO_DEPENDEND_FIELDS type')], verbose_name='Question Type'),
        ),
    ]
