# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20161228_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='survey_item',
        ),
        migrations.AddField(
            model_name='response',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='response',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Region'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
