# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20161229_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='HCPCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datetime of creation')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='hcp_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.HCPCategory'),
            preserve_default=False,
        ),
    ]
