# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20170110_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='hcp_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.HCPCategory'),
        ),
    ]
