# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170121_1147'),
        ('survey', '0006_answer_is_updated'),
    ]

    operations = [
    ]
