# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_merge_20170121_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_order',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Order in reports'),
        ),
    ]
