# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_question_report_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='report_order',
        ),
    ]
