# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_remove_question_report_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='report_order',
            new_name='ordering',
        ),
    ]
