# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20170124_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
    ]
