# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20170126_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['ordering', 'id']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['ordering', 'id']},
        ),
    ]
