# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20170126_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='label1',
            field=models.CharField(default='', max_length=200, verbose_name='Label1 for reports'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Organization name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_plural',
            field=models.CharField(default='', max_length=100, verbose_name='Organization name in plural form'),
        ),
        migrations.AddField(
            model_name='organization',
            name='name_plural_short',
            field=models.CharField(default='', max_length=100, verbose_name='Short organization name in plural form'),
        ),
    ]
