# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171225_0841'),
        ('survey', '0016_auto_20170130_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Question text')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Language')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Question')),
            ],
        ),
    ]
