# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20171225_1341'),
        ('survey', '0017_questiontranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='therapeutic_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TherapeuticArea'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.Question'),
        ),
    ]
