# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-29 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_survey_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='surveys', to='survey.Organization'),
        ),
    ]
