# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-05 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_eliminate_survey_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyitem',
            name='question',
        ),
        migrations.RemoveField(
            model_name='surveyitem',
            name='survey',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['survey_id', 'ordering', 'created_at']},
        ),
        migrations.DeleteModel(
            name='SurveyItem',
        ),
    ]
