# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20180106_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Survey slug'),
        ),
    ]
