# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-07 03:27
from __future__ import unicode_literals

from django.db import migrations
from django.template.defaultfilters import slugify


def populate_slug(apps, schema_editor):
    surveys = set()
    slugs = set()

    Survey = apps.get_model('survey', 'Survey')
    for s in Survey.objects.all():
        while s.name in surveys:
            s.name += '-'
        surveys.add(s.name)

        if s.slug is None or s.slug == '':
            s.slug = slugify(s.name)
        while s.slug in slugs:
            s.slug += '-'
        slugs.add(s.slug)

        s.save()


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_survey_slug'),
    ]

    operations = [
        migrations.RunPython(populate_slug, dummy),
    ]
