# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-09 06:00
from __future__ import unicode_literals

from django.db import migrations


def populate_survey(apps, schema_editor):
    Survey = apps.get_model('survey', 'Survey')
    Organization = apps.get_model('survey', 'Organization')
    Country = apps.get_model('users', 'Country')

    for s in Survey.objects.all():
        s.organizations = Organization.objects.all()
        s.countries = Country.objects.all()


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_auto_20180107_1921'),
        ('users', '0014_auto_20180106_0559'),
    ]

    operations = [
        migrations.RunPython(populate_survey, dummy),
    ]
