# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20180109_0758'),
    ]

    operations = [
        migrations.RenameField('Question', 'depends_of', 'depends_on'),
    ]
