# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0033_rename_depends_of_to_depends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dependency_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Question is included to other question with TYPE_TWO_DEPENDEND_FIELDS type'), (2, 'Question availability depends on other question')], null=True, verbose_name='Dependency Type'),
        ),
    ]
