# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_auto_20180112_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='available_if',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dependent question answer'),
        ),
    ]
