# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-28 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0037_question_is_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='unit',
            field=models.CharField(max_length=10, null=True, verbose_name='Unit'),
        ),
    ]
